---
title: "Comps"
---

# Part I

## Casella notes

- [Chapter 6 sufficient statistics](Chapter 6 sufficient statistics.pdf)
- [Chapter 7 point estimate](Chapter 7 point estimate.pdf)
- [Chapter 8 hypothesis testing](Chapter 8 hypothesis testing.pdf)
- [Chapterf 9 interval estimation](Chapter 9 interval estimation.pdf)
- [Chapter 10 hypothesis testing](Chapter 10 hypothesis testing.pdf)

## Side notes

- [Properties of MLE](MLE.pdf)
- [Properties of sample mean](sample mean properties.pdf)
- [Normal sample mean](Normal sample mean.pdf)
- [Normal sample variance](Normal sample variance.pdf)
- [Geometric and negative binomial connection](Geometric and negative binomial.pdf)
- [CLT proof](CLT proof.pdf)
- [Delta method](Delta method.pdf)
- [Markov chains](Markov chains.pdf); [Stochastic process](Stochastic process.pdf)
- [Linear regression](Linear regression.pdf)
- [Order statistics](Order statistics.pdf)
- [T distribution](T distribution.pdf)
- [2-dimensional normal PDF](2-dimensional normal PDF.pdf)
- [Exponential family and location-scale](Exponential family and location-scale.pdf)
- [Uniform convolution](Uniform convolution.pdf)
- [Generating random variables](Generating random variables.pdf)

## Past exams

# Part II

# Part III

- [Github repo](https://github.com/thisislinyu/2024PARTIII)

- [Report](Part III Report.pdf)

# Reference materials

## 数理统计相关
1. Mathematical statistics by Keith Knight. [\[book\]](books/mathematical_statistics.pdf), [\[solution\]](books/Mathematical_Statistics_solution.pdf)          
2. Introduction to Probability Models by Sheldon M. Ross eleventh edition. [\[book\]](books/introduction_to_probability.pdf)      
3. Statistical Inference by George Casella & Roger L. Berger second edition  [\[book\]](books/statistical_inference.pdf)       
4. All of Statistics by Larry       Wasserman[\[book\]](books/all_of_statistics.pdf)     

## 贝叶斯相关            
1. Bayesian Data Analysis by Andrew Gelman, John B. Carlin and others third edition [\[book\]](books/bayesian_data_analysis.pdf).  [\[lecture\]](https://avehtari.github.io/BDA_course_Aalto/)   by Aki Vehtari  

## large sample 相关
1. A Course in Large Sample Theory by Thomas S. Ferguson.[\[book\]](books/a_course_in_large_sample_theory.pdf)

## 生存分析相关

## 生物统计相关
1. Agresti categorical data analysis [\[book\]](books/AGRESTI_categorical_data_analysis_2nd.pdf)[\[solution\]](books/agresti_2nded_solutions_odd.pdf).
